ckpt_path: null

model:
  class_path: models.Yolo
  init_args:
    num_classes: 2
    loss_ratio: 0.1
    time_window: 0
    iou_threshold: 0.4
    learning_rate: 0.001
    state_storage: false
    init_weights: true

data:
  data_dir: ./data
  dataset: gen1
  batch_size: 1
  num_workers: 4
  num_load_file: 8
  num_steps: 32
  time_step: 16
  time_shift: 8
  one_label: true

trainer:
  accelerator: gpu
  strategy: auto
  devices: -1
  num_nodes: 1