### Basic
Mode: 2               # 1 - interactive, 2 - train, 3 - eval

### Train mode
LoadParameters: false
NumTrainRounds: -1     # -1 - infinite
NumRoundEpoch: 15
### Eval mode
NumEvalRounds: 10

### Model parameters
Backbone: res5
Neck: ssd3
Head: main
InitWeights: false
LossRatio: 0.1

### Dataset parameters
Dataset: gen1
TimeStep: 16
TimeWindow: 8
NumLoadFile: 8
NumWorkers: 4
# Train dataset
BatchSize: 6
NumSteps: 32
# Test dataset
TestBatchSize: 1
TestNumSteps: 128

### Progress board parameters
Display: True
EveryN: 4

### Plotter parameters
PlotterThreshold: 0.01
PlotterColumns: 4

### Trainer board parameters
NumGpus: 1
EpochSize: 60
