### Basic
Mode: 1               # 1 - interactive, 2 - train, 3 - eval

### Train mode
LoadParameters: false
NumTrainRounds: 8     # -1 - infinite
NumRoundEpoch: 15
### Eval mode
NumEvalRounds: 10

### Model parameters
BackboneName: resnet     # vgg, resnet
BackboneVersion: m
NeckName: ssd
NeckVersion: 3
BatchNorm: true
InitWeights: false
Dropout: false
LossRatio: 0.08

### Dataset parameters
Dataset: gen1
TimeStep: 16
TimeWindow: 16
NumLoadFile: 8
NumWorkers: 4
# Train dataset
BatchSize: 2
NumSteps: 32
# Test dataset
TestBatchSize: 1
TestNumSteps: 128

### Progress board parameters
Display: True
EveryN: 4

### Plotter parameters
PlotterThreshold: 0.01
PlotterColumns: 4

### Trainer board parameters
NumGpus: 1
EpochSize: 200
