### Basic
Mode: 2               # 1 - interactive, 2 - train, 3 - eval, 4 - activity test
gpu_index: 0
SaveFolder: timeshift_8

### Train mode
LoadParameters: true
NumTrainRounds: -1    # -1 - infinite
NumRoundEpoch: 30
### Eval mode
NumEvalRounds: 300

### Model parameters
Model: yolo           # yolo
InitWeights: true
LossRatio: 0.04

### Dataset parameters
Dataset: gen1
TimeStep: 16
NumLoadFile: 8
NumWorkers: 4
# Train dataset
BatchSize: 5
NumSteps: 32
TimeWindow: 8
TimeShift: 8
# Test dataset
TestBatchSize: 64
TestNumSteps: 32

### Progress board parameters
Display: True
EveryN: 4

### Plotter parameters
PlotterThreshold: 0.1
PlotterColumns: 4

### Trainer board parameters
EpochSize: 60
