# ckpt_path: "nets/tiny_yolo/tiny_yolo_gen1.ckpt"

model:
  class_path: models.Yolo
  init_args:
    model: n
    num_classes: 2
    loss_ratio: 0.04
    time_window: 32
    iou_threshold: 0.4
    learning_rate: 0.001
    state_storage: false
    init_weights: true
    plotter:
      class_path: utils.Plotter
      init_args:
        threshold: 0.8
        show_video: true
        save_video: false
        file_path: log
        file_name: out

data:
  data_dir: ./data
  dataset: gen1
  batch_size: 10
  num_workers: 4
  num_load_file: 8
  num_steps: 64
  time_step: 8
  time_shift: 0
  one_label: true
  # Must be a multiple of 32 for yolo
  resize: [256, 320]

trainer:
  accelerator: gpu
  strategy: ddp
  devices: -1
  num_nodes: 1
  precision: null
  callbacks:
    - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: map
        mode: max
        patience: 30
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: map
        save_top_k: 4
        mode: max
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: 3
  fast_dev_run: false
  max_epochs: -1
  min_epochs: 2500
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 100
  limit_val_batches: 100
  limit_test_batches: 1000
  limit_predict_batches: null
  overfit_batches: 0.0
  check_val_every_n_epoch: 10
  num_sanity_val_steps: 0
  log_every_n_steps: 20
  enable_checkpointing: True
  accumulate_grad_batches: 1
  gradient_clip_algorithm: null
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins:
  #    class_path: lightning.pytorch.plugins.environments.SLURMEnvironment
  sync_batchnorm: true
  reload_dataloaders_every_n_epochs: 0
