# lightning.pytorch==2.5.0.post0
seed_everything: true
trainer:
  accelerator: gpu
  strategy: auto
  devices: -1
  num_nodes: 1
  precision: null
  callbacks: null
  fast_dev_run: false
  max_epochs: -1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 100
  limit_val_batches: 100
  limit_test_batches: 100
  limit_predict_batches: 1
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 10
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: True
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_algorithm: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
model:
  num_classes: 2
  loss_ratio: 0.04
  time_window: 0
  iou_threshold: 0.4
  learning_rate: 0.001
  state_storage: false
  init_weights: true
data:
  data_dir: ./data
  dataset: gen1
  batch_size: 4
  num_workers: 4
  num_load_file: 8
  num_steps: 32
  time_step: 16
  time_shift: 8
  one_label: true
optimizer: null
lr_scheduler: null
ckpt_path: null
