trainer:
  accelerator: gpu
  strategy: ddp
  devices: -1
  num_nodes: 1
  precision: null
  callbacks:
    - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: map
        mode: max
        patience: 20
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: map
        save_top_k: 2
        mode: max
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
          max_depth: 1
  fast_dev_run: false
  max_epochs: -1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 100
  limit_val_batches: 100
  limit_test_batches: 100
  limit_predict_batches: 20
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  log_every_n_steps: null
  enable_checkpointing: True
  accumulate_grad_batches: 1
  gradient_clip_algorithm: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins:
#    class_path: lightning.pytorch.plugins.environments.SLURMEnvironment
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0